/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin05_gradle

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

class Hello() {
    companion object {
        val greeting: String
        get() {
            return "Hello"
        }
    }
}

fun main() {
    println(App().greeting)
    println(Hello.greeting)
}
